version: '3.9'

services:
  db:
    container_name: gigacounts-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=p@ssword
      - POSTGRES_USER=admin
      - POSTGRES_DB=unicef-giga
    volumes:
      - ./database/scripts/db-mocks:/docker-entrypoint-initdb.d