# The workflow for adding an user to a gnosis safe on ethereum blockchain

name: Assign User to Safe

on:
  workflow_dispatch:
    inputs:
      user_email:
        description: 'User Email'
        required: true
      target_env:
        description: 'Target ENV'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - uat

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: Build Job
    env:
      USER_EMAIL: ${{ github.event.inputs.user_email }}
      SAFE_TARGET_ENV: ${{ github.event.inputs.target_env }}

    steps:
      - name: Get token
        run: |
          export TOKEN=$(jq '.token' <(echo "$(curl -L -XPOST 'https://unicef-giga-backend-${{ env.SAFE_TARGET_ENV }}.azurewebsites.net/login' -H 'Content-Type:application/json' -d '{"email":"${{ secrets.DEV_BACKEND_USERNAME }}","password":"${{ secrets.DEV_BACKEND_PASSWORD }}"}')") | sed "s/\"//g")
          echo "BEARER_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Add User to safe
        run: |
          echo "$(curl -L -XPOST 'https://unicef-giga-backend-${{ env.SAFE_TARGET_ENV }}.azurewebsites.net/safe/add-user' -H "Authorization: Bearer $BEARER_TOKEN" -H "Content-Type:application/json" -d '{"email":"${{ env.USER_EMAIL }}"}')"
