# The workflow for creating a gnosis safe on ethereum blockchain

name: Create Safe

on:
  workflow_dispatch:
    inputs:
      safe_name:
        description: 'Safe name'
        required: true
      target_env:
        description: 'Target ENV'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - uat

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: Build Job
    env:
      SAFE_NAME: ${{ github.event.inputs.safe_name }}
      SAFE_TARGET_ENV: ${{ github.event.inputs.target_env }}

    steps:
      - name: Get token
        run: |
          export TOKEN=$(jq '.token' <(echo "$(curl -L -XPOST 'https://unicef-giga-backend-${{ env.CRON_TARGET_ENV }}.azurewebsites.net/login' -H 'Content-Type:application/json' -d '{"email":"${{ secrets.DEV_BACKEND_USERNAME }}","password":"${{ secrets.DEV_BACKEND_PASSWORD }}"}')") | sed "s/\"//g")
          echo "BEARER_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Create safe
        run: |
          echo "$(curl -L -XPOST 'https://unicef-giga-backend-${{ env.CRON_TARGET_ENV }}.azurewebsites.net/safe' -H 'Content-Type:application/json' -d '{"email":"${{ secrets.DEV_BACKEND_USERNAME }}","password":"${{ secrets.DEV_BACKEND_PASSWORD }}"}')"
